ALTER TABLE "StadtlaufBS"."DISPOSITIV" DROP CONSTRAINT "fk_DISPOSITIV_SEKTOR_AKTIV" CASCADE;
ALTER TABLE "StadtlaufBS"."AUSTRAGUNG" DROP CONSTRAINT "fk_AUSTRAGUNG_ANLASS" CASCADE;
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" DROP CONSTRAINT "fk_SEKTOR_AKTIV_AUSTRAGUNG" CASCADE;
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" DROP CONSTRAINT "fk_SEKTOR_AKTIV_SEKTOR" CASCADE;
ALTER TABLE "StadtlaufBS"."DOK_INHALT" DROP CONSTRAINT "fk_DOK_INHALT_DOKUMENT" CASCADE;
ALTER TABLE "StadtlaufBS"."DOK_INHALT" DROP CONSTRAINT "fk_DOK_INHALT_POSITION_TYP" CASCADE;
ALTER TABLE "StadtlaufBS"."AUSRUESTUNG" DROP CONSTRAINT "fk_AUSRUESTUNG_POSITION" CASCADE;
ALTER TABLE "StadtlaufBS"."AUSRUESTUNG" DROP CONSTRAINT "fk_AUSRUESTUNG_MATERIAL" CASCADE;
ALTER TABLE "StadtlaufBS"."VORSIGNAL" DROP CONSTRAINT "fk_VORSIGNAL_POSITION" CASCADE;
ALTER TABLE "StadtlaufBS"."VORSIGNAL" DROP CONSTRAINT "fk_VORSIGNAL_MATERIAL" CASCADE;
ALTER TABLE "StadtlaufBS"."BESATZUNG" DROP CONSTRAINT "fk_BESATZUNG_POSITION" CASCADE;
ALTER TABLE "StadtlaufBS"."BESATZUNG" DROP CONSTRAINT "fk_BESATZUNG_PERSONAL_TYP" CASCADE;
ALTER TABLE "StadtlaufBS"."VORSIGNAL" DROP CONSTRAINT "fk_VORSIGNAL_PERSONAL_TYP" CASCADE;
ALTER TABLE "StadtlaufBS"."DISPOSITIV" DROP CONSTRAINT "fk_DISPOSITIV_POSITION" CASCADE;
ALTER TABLE "StadtlaufBS"."POSITION" DROP CONSTRAINT "fk_POSITION_POSITION_TYP" CASCADE;
ALTER TABLE "StadtlaufBS"."POSITION" DROP CONSTRAINT "fk_POSITION_LIEFER_POS" CASCADE;
ALTER TABLE "StadtlaufBS"."MATERIAL" DROP CONSTRAINT "fk_MATERIAL_LIEFERART" CASCADE;
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" DROP CONSTRAINT "fk_SEKTOR_AKTIV_POSITION_BS" CASCADE;
ALTER TABLE "StadtlaufBS"."EINSATZ" DROP CONSTRAINT "fk_EINSATZ_HELFER" CASCADE;
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" DROP CONSTRAINT "fk_SEKTOR_AKTIV_POSITION_LF" CASCADE;
ALTER TABLE "StadtlaufBS"."DOK_INHALT" DROP CONSTRAINT "fk_DOK_INHALT_SEKTOR_TYP" CASCADE;
ALTER TABLE "StadtlaufBS"."SEKTOR" DROP CONSTRAINT "fk_SEKTOR_SEKTOR_TYP" CASCADE;
ALTER TABLE "StadtlaufBS"."EINSATZ" DROP CONSTRAINT "fk_EINSATZ_BESATZUNG" CASCADE;
ALTER TABLE "StadtlaufBS"."BELIEFERUNG" DROP CONSTRAINT "fk_BELIEFERUNG_SEKTOR_DISPO" CASCADE;
ALTER TABLE "StadtlaufBS"."BELIEFERUNG" DROP CONSTRAINT "fk_BELIEFERUNG_SEKTOR_LFRG" CASCADE;
ALTER TABLE "StadtlaufBS"."DOK_INHALT" DROP CONSTRAINT "fk_DOK_INHALT_LIEFERART" CASCADE;

DROP INDEX "StadtlaufBS"."pk_ANLASS" CASCADE;
DROP INDEX "StadtlaufBS"."pk_AUSTRAGUNG" CASCADE;
DROP INDEX "StadtlaufBS"."fk_AUSTRAGUNG_ANLASS" CASCADE;
DROP INDEX "StadtlaufBS"."pk_SEKTOR" CASCADE;
DROP INDEX "StadtlaufBS"."fk_SEKTOR_SEKTOR_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."pk_POSITION" CASCADE;
DROP INDEX "StadtlaufBS"."fk_POSITION_POSITION_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."fk_POSITION_LIEFER_POS" CASCADE;
DROP INDEX "StadtlaufBS"."pk_DISPOSITIV" CASCADE;
DROP INDEX "StadtlaufBS"."fk_DISPOSITIV_SEKTOR_AKTIV" CASCADE;
DROP INDEX "StadtlaufBS"."fk_DISPOSITIV_POSITION" CASCADE;
DROP INDEX "StadtlaufBS"."pk_SEKTOR_AKTIV" CASCADE;
DROP INDEX "StadtlaufBS"."fk_SEKTOR_AKTIV_AUSTRAGUNG" CASCADE;
DROP INDEX "StadtlaufBS"."fk_SEKTOR_AKTIV_SEKTOR" CASCADE;
DROP INDEX "StadtlaufBS"."fk_SEKTOR_AKTIV_POSITION" CASCADE;
DROP INDEX "StadtlaufBS"."pk_MATERIAL" CASCADE;
DROP INDEX "StadtlaufBS"."fk_MATERIAL_LIEFERART" CASCADE;
DROP INDEX "StadtlaufBS"."pk_AUSRUESTUNG" CASCADE;
DROP INDEX "StadtlaufBS"."fk_AUSRUESTUNG_POSITION" CASCADE;
DROP INDEX "StadtlaufBS"."fk_AUSRUESTUNG_MATERIAL" CASCADE;
DROP INDEX "StadtlaufBS"."pk_PERSONAL_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."pk_BESATZUNG" CASCADE;
DROP INDEX "StadtlaufBS"."fk_BESATZUNG_POSITION" CASCADE;
DROP INDEX "StadtlaufBS"."fk_BESATZUNG_PERSONAL_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."ak_BESATZUNG" CASCADE;
DROP INDEX "StadtlaufBS"."pk_POSITION_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."pk_DOKUMENT" CASCADE;
DROP INDEX "StadtlaufBS"."pk_DOKU_INHALT" CASCADE;
DROP INDEX "StadtlaufBS"."fk_DOK_INHALT_DOKUMENT" CASCADE;
DROP INDEX "StadtlaufBS"."fk_DOK_INHALT_POSITION_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."fk_DOK_INHALT_SEKTOR_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."fk_DOK_INHALT_LIEFERART" CASCADE;
DROP INDEX "StadtlaufBS"."pk_VORSIGNAL" CASCADE;
DROP INDEX "StadtlaufBS"."fk_VORSIGNAL_POSITION" CASCADE;
DROP INDEX "StadtlaufBS"."fk_VORSIGNAL_MATERIAL" CASCADE;
DROP INDEX "StadtlaufBS"."fk_VORSIGNAL_PERSONAL_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."pk_LIEFERART" CASCADE;
DROP INDEX "StadtlaufBS"."pk_HELFER" CASCADE;
DROP INDEX "StadtlaufBS"."fk_EINSATZ_HELFER" CASCADE;
DROP INDEX "StadtlaufBS"."fk_EINSATZ_BESATZUNG" CASCADE;
DROP INDEX "StadtlaufBS"."pk_EINSATZ" CASCADE;
DROP INDEX "StadtlaufBS"."pk_SEKTOR_TYP" CASCADE;
DROP INDEX "StadtlaufBS"."pk_BELIEFERUNG" CASCADE;
DROP INDEX "StadtlaufBS"."fk_BELIEFERUNG_SEKTOR_DISPO" CASCADE;
DROP INDEX "StadtlaufBS"."fk_BELIEFERUNG_SEKTOR_LFRG" CASCADE;
DROP INDEX "StadtlaufBS"."ak_BELIEFERUNG" CASCADE;

DROP TABLE "StadtlaufBS"."ANLASS" CASCADE;
DROP TABLE "StadtlaufBS"."AUSTRAGUNG" CASCADE;
DROP TABLE "StadtlaufBS"."SEKTOR" CASCADE;
DROP TABLE "StadtlaufBS"."POSITION" CASCADE;
DROP TABLE "StadtlaufBS"."DISPOSITIV" CASCADE;
DROP TABLE "StadtlaufBS"."SEKTOR_AKTIV" CASCADE;
DROP TABLE "StadtlaufBS"."MATERIAL" CASCADE;
DROP TABLE "StadtlaufBS"."AUSRUESTUNG" CASCADE;
DROP TABLE "StadtlaufBS"."PERSONAL_TYP" CASCADE;
DROP TABLE "StadtlaufBS"."BESATZUNG" CASCADE;
DROP TABLE "StadtlaufBS"."POSITION_TYP" CASCADE;
DROP TABLE "StadtlaufBS"."DOKUMENT" CASCADE;
DROP TABLE "StadtlaufBS"."DOK_INHALT" CASCADE;
DROP TABLE "StadtlaufBS"."VORSIGNAL" CASCADE;
DROP TABLE "StadtlaufBS"."LIEFERART" CASCADE;
DROP TABLE "StadtlaufBS"."HELFER" CASCADE;
DROP TABLE "StadtlaufBS"."EINSATZ" CASCADE;
DROP TABLE "StadtlaufBS"."SEKTOR_TYP" CASCADE;
DROP TABLE "StadtlaufBS"."BELIEFERUNG" CASCADE;

CREATE TABLE "StadtlaufBS"."ANLASS" (
"ANLASS_ID" serial4 NOT NULL,
"ANLASS_NM" varchar(128) NOT NULL,
"ANLASS_DSC" varchar(256),
"ANLASS_LOGO_URL" varchar(512),
"POLIZEI_ABTEILUNG_NM" varchar(256) NOT NULL,
"POLIZEI_LOGO_URL" varchar(512),
"DISPO_DOKU_TI" varchar(32) NOT NULL,
PRIMARY KEY ("ANLASS_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_ANLASS" ON "StadtlaufBS"."ANLASS" USING btree ("ANLASS_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."ANLASS" IS 'Stamminformationen eines Anlasses';
ALTER TABLE "StadtlaufBS"."ANLASS" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."AUSTRAGUNG" (
"AUSTRAGUNG_ID" serial4 NOT NULL,
"ANLASS_ID" int4 NOT NULL,
"AUSTRAGUNG_DT" date NOT NULL,
"AUSTRAGUNG_ZUS_DSC" varchar(128),
"PLAN_VERKEHRSREGIME_URL" varchar(512),
PRIMARY KEY ("AUSTRAGUNG_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_AUSTRAGUNG" ON "StadtlaufBS"."AUSTRAGUNG" USING btree ("AUSTRAGUNG_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_AUSTRAGUNG_ANLASS" ON "StadtlaufBS"."AUSTRAGUNG" USING btree ("ANLASS_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."AUSTRAGUNG" IS 'Ausführung eines Anlasses';
ALTER TABLE "StadtlaufBS"."AUSTRAGUNG" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."SEKTOR" (
"SEKTOR_ID" serial4 NOT NULL,
"SEKTOR_BZ" varchar(32) NOT NULL,
"SEKTOR_NM" varchar(128),
"SEKTOR_TYP_ID" int4 NOT NULL,
PRIMARY KEY ("SEKTOR_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_SEKTOR" ON "StadtlaufBS"."SEKTOR" USING btree ("SEKTOR_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_SEKTOR_SEKTOR_TYP" ON "StadtlaufBS"."SEKTOR" USING btree ("SEKTOR_TYP_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."SEKTOR" IS 'Grundlegende Informationen des Sektors';
ALTER TABLE "StadtlaufBS"."SEKTOR" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."POSITION" (
"POSITION_ID" serial4 NOT NULL,
"POSITION_DSC" varchar(128) NOT NULL,
"ORTSCHAFT_TX" varchar(256) NOT NULL,
"OERTLICHKEIT_TX" varchar(256) NOT NULL,
"ABSCHNITT_TX" varchar(256) NOT NULL,
"BEREIT_ZT" time(6) NOT NULL,
"SPERRE_AB_ZT" time(6) NOT NULL,
"SPERRE_BIS_ZT" time(6) NOT NULL,
"AUFTRAG_ANW" varchar(512) NOT NULL,
"MASSNAHME_ANW" varchar(512),
"AUFBAU_ANW" varchar(256),
"SITUATION_BILD_URL" varchar(512),
"POSITION_TYP_ID" int4 NOT NULL,
"LIEFER_POS_ID" int4,
PRIMARY KEY ("POSITION_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_POSITION" ON "StadtlaufBS"."POSITION" USING btree ("POSITION_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_POSITION_POSITION_TYP" ON "StadtlaufBS"."POSITION" USING btree ("POSITION_TYP_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_POSITION_LIEFER_POS" ON "StadtlaufBS"."POSITION" USING btree ("LIEFER_POS_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."POSITION" IS 'Detailinformationen einer Position';
ALTER TABLE "StadtlaufBS"."POSITION" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."DISPOSITIV" (
"SEKTOR_AKTIV_ID" int4 NOT NULL,
"POSITION_ID" int4 NOT NULL,
"POSITION_NR" int4,
"POSITION_TX" varchar(3),
"POSITION_BZ" varchar(32),
PRIMARY KEY ("SEKTOR_AKTIV_ID", "POSITION_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_DISPOSITIV" ON "StadtlaufBS"."DISPOSITIV" USING btree ("SEKTOR_AKTIV_ID" ASC, "POSITION_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_DISPOSITIV_SEKTOR_AKTIV" ON "StadtlaufBS"."DISPOSITIV" USING btree ("SEKTOR_AKTIV_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_DISPOSITIV_POSITION" ON "StadtlaufBS"."DISPOSITIV" USING btree ("POSITION_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."DISPOSITIV" IS 'Eigentliches Dispositiv einer Austragung';
ALTER TABLE "StadtlaufBS"."DISPOSITIV" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."SEKTOR_AKTIV" (
"SEKTOR_AKTIV_ID" serial4 NOT NULL,
"AUSTRAGUNG_ID" int4 NOT NULL,
"SEKTOR_ID" int4 NOT NULL,
"SEKTOR_CHEF_NM" varchar(128) NOT NULL,
"BESAMMLUNG_ZT" time(6) NOT NULL,
"BESAMMLUNG_ORT_ID" int4,
"POSITION_LIEFERUNG_ID" int4,
"SEKTOR_SRT" int4 NOT NULL,
"PLAN_DISPOSITIV_URL" varchar(512),
"PLAN_POSITIONEN_URL" varchar(512),
"PLAN_BESAMMLUNG_URL" varchar(512),
"PLAN_LIEFERORTE_URL" varchar(512),
PRIMARY KEY ("SEKTOR_AKTIV_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_SEKTOR_AKTIV" ON "StadtlaufBS"."SEKTOR_AKTIV" USING btree ("SEKTOR_AKTIV_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_SEKTOR_AKTIV_AUSTRAGUNG" ON "StadtlaufBS"."SEKTOR_AKTIV" USING btree ("AUSTRAGUNG_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_SEKTOR_AKTIV_SEKTOR" ON "StadtlaufBS"."SEKTOR_AKTIV" USING btree ("SEKTOR_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_SEKTOR_AKTIV_POSITION" ON "StadtlaufBS"."SEKTOR_AKTIV" USING btree ("BESAMMLUNG_ORT_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."SEKTOR_AKTIV" IS 'Benutzte Sektoren eines Anlasses';
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."MATERIAL" (
"MATERIAL_ID" serial4 NOT NULL,
"MATERIAL_BZ" varchar(32) NOT NULL,
"MATERIAL_NM" varchar(128) NOT NULL,
"MATERIAL_ICON_URL" varchar(512),
"LIEFERART_ID" int4 NOT NULL,
PRIMARY KEY ("MATERIAL_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_MATERIAL" ON "StadtlaufBS"."MATERIAL" USING btree ("MATERIAL_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_MATERIAL_LIEFERART" ON "StadtlaufBS"."MATERIAL" USING btree ("LIEFERART_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."MATERIAL" IS 'Material-Stammdaten';
ALTER TABLE "StadtlaufBS"."MATERIAL" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."AUSRUESTUNG" (
"POSITION_ID" int4 NOT NULL,
"MATERIAL_ID" int4 NOT NULL,
"AUSRUESTUNG_AZ" int4 NOT NULL,
PRIMARY KEY ("POSITION_ID", "MATERIAL_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_AUSRUESTUNG" ON "StadtlaufBS"."AUSRUESTUNG" USING btree ("POSITION_ID" ASC, "MATERIAL_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_AUSRUESTUNG_POSITION" ON "StadtlaufBS"."AUSRUESTUNG" USING btree ("POSITION_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_AUSRUESTUNG_MATERIAL" ON "StadtlaufBS"."AUSRUESTUNG" USING btree ("MATERIAL_ID" ASC) TABLESPACE "pg_default";
ALTER TABLE "StadtlaufBS"."AUSRUESTUNG" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."PERSONAL_TYP" (
"PERSONAL_TYP_ID" serial4 NOT NULL,
"PERSONAL_TYP_BZ" varchar(32) NOT NULL,
"PERSONAL_TYP_NM" varchar(128) NOT NULL,
"PERSONAL_TYP_ICON_URL" varchar(512),
PRIMARY KEY ("PERSONAL_TYP_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_PERSONAL_TYP" ON "StadtlaufBS"."PERSONAL_TYP" USING btree ("PERSONAL_TYP_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."PERSONAL_TYP" IS 'Personal-Stamm-Daten';
ALTER TABLE "StadtlaufBS"."PERSONAL_TYP" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."BESATZUNG" (
"BESATZUNG_ID" serial4 NOT NULL,
"POSITION_ID" int4 NOT NULL,
"PERSONAL_TYP_ID" int4 NOT NULL,
"PERSONAL_AZ" int4 NOT NULL,
"AUFTRAG_SPZ_ANW" varchar(512),
PRIMARY KEY ("BESATZUNG_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_BESATZUNG" ON "StadtlaufBS"."BESATZUNG" USING btree ("BESATZUNG_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_BESATZUNG_POSITION" ON "StadtlaufBS"."BESATZUNG" USING btree ("POSITION_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_BESATZUNG_PERSONAL_TYP" ON "StadtlaufBS"."BESATZUNG" USING btree ("PERSONAL_TYP_ID" ASC) TABLESPACE "pg_default";
CREATE UNIQUE INDEX "ak_BESATZUNG" ON "StadtlaufBS"."BESATZUNG" USING btree ("POSITION_ID" ASC, "PERSONAL_TYP_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."BESATZUNG" IS 'Benötigte Besatzung der Position';
ALTER TABLE "StadtlaufBS"."BESATZUNG" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."POSITION_TYP" (
"POSITION_TYP_ID" serial4 NOT NULL,
"POSITION_TYP_BZ" varchar(128) NOT NULL,
"DISPOBLATT_JN" bool NOT NULL,
"MATERIALLISTE_JN" bool NOT NULL,
"MATERIALLIEFERUNG_JN" bool NOT NULL,
PRIMARY KEY ("POSITION_TYP_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_POSITION_TYP" ON "StadtlaufBS"."POSITION_TYP" USING btree ("POSITION_TYP_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."POSITION_TYP" IS 'Typ einer Position (Dispo, Materiallieferung etc.)';
ALTER TABLE "StadtlaufBS"."POSITION_TYP" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."DOKUMENT" (
"DOKUMENT_ID" serial4 NOT NULL,
"DOKUMENT_TI" varchar(128) NOT NULL,
"DOKUMENT_PGM" varchar(256) NOT NULL,
"DOKUMENT_ERGAENZUNG_URL" varchar(512),
PRIMARY KEY ("DOKUMENT_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_DOKUMENT" ON "StadtlaufBS"."DOKUMENT" USING btree ("DOKUMENT_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."DOKUMENT" IS 'Beschreibung des Dokumentes';
ALTER TABLE "StadtlaufBS"."DOKUMENT" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."DOK_INHALT" (
"DOKUMENT_ID" int4 NOT NULL,
"POSITION_TYP_ID" int4 NOT NULL,
"SEKTOR_TYP_ID" int4 NOT NULL,
"LIEFERART_ID" int4 NOT NULL,
PRIMARY KEY ("DOKUMENT_ID", "POSITION_TYP_ID", "SEKTOR_TYP_ID", "LIEFERART_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_DOKU_INHALT" ON "StadtlaufBS"."DOK_INHALT" USING btree ("DOKUMENT_ID" ASC, "POSITION_TYP_ID" ASC, "SEKTOR_TYP_ID" ASC, "LIEFERART_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_DOK_INHALT_DOKUMENT" ON "StadtlaufBS"."DOK_INHALT" USING btree ("DOKUMENT_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_DOK_INHALT_POSITION_TYP" ON "StadtlaufBS"."DOK_INHALT" USING btree ("POSITION_TYP_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_DOK_INHALT_SEKTOR_TYP" ON "StadtlaufBS"."DOK_INHALT" USING btree ("SEKTOR_TYP_ID" ASC);
CREATE INDEX "fk_DOK_INHALT_LIEFERART" ON "StadtlaufBS"."DOK_INHALT" USING btree ("LIEFERART_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."DOK_INHALT" IS 'Zuordnung von Positionstypen zu Dokumenten';
ALTER TABLE "StadtlaufBS"."DOK_INHALT" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."VORSIGNAL" (
"VORSIGNAL_ID" serial4 NOT NULL,
"POSITION_ID" int4 NOT NULL,
"MATERIAL_ID" int4 NOT NULL,
"VORSIGNAL_ORT_TX" varchar(256) NOT NULL,
"PERSONAL_TYP_ID" int4,
PRIMARY KEY ("VORSIGNAL_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_VORSIGNAL" ON "StadtlaufBS"."VORSIGNAL" USING btree ("VORSIGNAL_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_VORSIGNAL_POSITION" ON "StadtlaufBS"."VORSIGNAL" USING btree ("POSITION_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_VORSIGNAL_MATERIAL" ON "StadtlaufBS"."VORSIGNAL" USING btree ("MATERIAL_ID" ASC) TABLESPACE "pg_default";
CREATE INDEX "fk_VORSIGNAL_PERSONAL_TYP" ON "StadtlaufBS"."VORSIGNAL" USING btree ("PERSONAL_TYP_ID" ASC) TABLESPACE "pg_default";
COMMENT ON TABLE "StadtlaufBS"."VORSIGNAL" IS 'Angaben zum Vorsignal';
ALTER TABLE "StadtlaufBS"."VORSIGNAL" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."LIEFERART" (
"LIEFERART_ID" serial4 NOT NULL,
"LIEFERART_BZ" varchar(32) NOT NULL,
"LIEFERART_DSC" varchar(512),
PRIMARY KEY ("LIEFERART_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_LIEFERART" ON "StadtlaufBS"."LIEFERART" USING btree ("LIEFERART_ID" ASC);
ALTER TABLE "StadtlaufBS"."LIEFERART" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."HELFER" (
"HELFER_ID" serial4 NOT NULL,
"HELFER_NM" varchar(255) NOT NULL,
"HELFER_EMAIL_ADR" varchar(255) NOT NULL,
"HELFER_TEL_NR" varchar(32) NOT NULL,
"HELFER_AZ" int4 NOT NULL,
PRIMARY KEY ("HELFER_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_HELFER" ON "StadtlaufBS"."HELFER" USING btree ("HELFER_ID" ASC);
ALTER TABLE "StadtlaufBS"."HELFER" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."EINSATZ" (
"BESATZUNG_ID" int4 NOT NULL,
"HELFER_ID" int4 NOT NULL,
"EINSATZ_AZ" int4 NOT NULL,
"EINSATZ_VON_ZT" time(6) NOT NULL,
"EINSATZ_BIS_ZT" time(6) NOT NULL,
"AUFTRAG_ZUS_ANW" varchar(256),
PRIMARY KEY ("BESATZUNG_ID", "HELFER_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE INDEX "fk_EINSATZ_HELFER" ON "StadtlaufBS"."EINSATZ" USING btree ("HELFER_ID" ASC);
CREATE INDEX "fk_EINSATZ_BESATZUNG" ON "StadtlaufBS"."EINSATZ" USING btree ("BESATZUNG_ID" ASC);
CREATE INDEX "pk_EINSATZ" ON "StadtlaufBS"."EINSATZ" USING btree ("BESATZUNG_ID" ASC, "HELFER_ID" ASC);
ALTER TABLE "StadtlaufBS"."EINSATZ" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."SEKTOR_TYP" (
"SEKTOR_TYP_ID" serial4 NOT NULL,
"SEKTOR_TYP_BZ" varchar(128),
PRIMARY KEY ("SEKTOR_TYP_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_SEKTOR_TYP" ON "StadtlaufBS"."SEKTOR_TYP" USING btree ("SEKTOR_TYP_ID" ASC);
COMMENT ON TABLE "StadtlaufBS"."SEKTOR_TYP" IS 'Verwendung des Sektors';
ALTER TABLE "StadtlaufBS"."SEKTOR_TYP" OWNER TO "postgres";

CREATE TABLE "StadtlaufBS"."BELIEFERUNG" (
"BELIEFERUNG_ID" serial4 NOT NULL,
"SEKTOR_AKTIV_ID_DISPO" int4 NOT NULL,
"SEKTOR_AKTIV_ID_LFRG" int4 NOT NULL,
"LFRG_SEKTOR_MAT_JN" bool NOT NULL,
PRIMARY KEY ("BELIEFERUNG_ID")
)
WITHOUT OIDS
TABLESPACE pg_default;
CREATE UNIQUE INDEX "pk_BELIEFERUNG" ON "StadtlaufBS"."BELIEFERUNG" USING btree ("BELIEFERUNG_ID" ASC);
CREATE INDEX "fk_BELIEFERUNG_SEKTOR_DISPO" ON "StadtlaufBS"."BELIEFERUNG" USING btree ("SEKTOR_AKTIV_ID_DISPO" ASC);
CREATE INDEX "fk_BELIEFERUNG_SEKTOR_LFRG" ON "StadtlaufBS"."BELIEFERUNG" USING btree ("SEKTOR_AKTIV_ID_LFRG" ASC);
CREATE UNIQUE INDEX "ak_BELIEFERUNG" ON "StadtlaufBS"."BELIEFERUNG" USING btree ("SEKTOR_AKTIV_ID_DISPO" ASC, "SEKTOR_AKTIV_ID_LFRG" ASC);
COMMENT ON TABLE "StadtlaufBS"."BELIEFERUNG" IS 'Zuordnung von Liefersektor zu Disposektor';
ALTER TABLE "StadtlaufBS"."BELIEFERUNG" OWNER TO "postgres";


ALTER TABLE "StadtlaufBS"."DISPOSITIV" ADD CONSTRAINT "fk_DISPOSITIV_SEKTOR_AKTIV" FOREIGN KEY ("SEKTOR_AKTIV_ID") REFERENCES "StadtlaufBS"."SEKTOR_AKTIV" ("SEKTOR_AKTIV_ID");
ALTER TABLE "StadtlaufBS"."AUSTRAGUNG" ADD CONSTRAINT "fk_AUSTRAGUNG_ANLASS" FOREIGN KEY ("ANLASS_ID") REFERENCES "StadtlaufBS"."ANLASS" ("ANLASS_ID");
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" ADD CONSTRAINT "fk_SEKTOR_AKTIV_AUSTRAGUNG" FOREIGN KEY ("AUSTRAGUNG_ID") REFERENCES "StadtlaufBS"."AUSTRAGUNG" ("AUSTRAGUNG_ID");
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" ADD CONSTRAINT "fk_SEKTOR_AKTIV_SEKTOR" FOREIGN KEY ("SEKTOR_ID") REFERENCES "StadtlaufBS"."SEKTOR" ("SEKTOR_ID");
ALTER TABLE "StadtlaufBS"."DOK_INHALT" ADD CONSTRAINT "fk_DOK_INHALT_DOKUMENT" FOREIGN KEY ("DOKUMENT_ID") REFERENCES "StadtlaufBS"."DOKUMENT" ("DOKUMENT_ID");
ALTER TABLE "StadtlaufBS"."DOK_INHALT" ADD CONSTRAINT "fk_DOK_INHALT_POSITION_TYP" FOREIGN KEY ("POSITION_TYP_ID") REFERENCES "StadtlaufBS"."POSITION_TYP" ("POSITION_TYP_ID");
ALTER TABLE "StadtlaufBS"."AUSRUESTUNG" ADD CONSTRAINT "fk_AUSRUESTUNG_POSITION" FOREIGN KEY ("POSITION_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."AUSRUESTUNG" ADD CONSTRAINT "fk_AUSRUESTUNG_MATERIAL" FOREIGN KEY ("MATERIAL_ID") REFERENCES "StadtlaufBS"."MATERIAL" ("MATERIAL_ID");
ALTER TABLE "StadtlaufBS"."VORSIGNAL" ADD CONSTRAINT "fk_VORSIGNAL_POSITION" FOREIGN KEY ("POSITION_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."VORSIGNAL" ADD CONSTRAINT "fk_VORSIGNAL_MATERIAL" FOREIGN KEY ("MATERIAL_ID") REFERENCES "StadtlaufBS"."MATERIAL" ("MATERIAL_ID");
ALTER TABLE "StadtlaufBS"."BESATZUNG" ADD CONSTRAINT "fk_BESATZUNG_POSITION" FOREIGN KEY ("POSITION_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."BESATZUNG" ADD CONSTRAINT "fk_BESATZUNG_PERSONAL_TYP" FOREIGN KEY ("PERSONAL_TYP_ID") REFERENCES "StadtlaufBS"."PERSONAL_TYP" ("PERSONAL_TYP_ID");
ALTER TABLE "StadtlaufBS"."VORSIGNAL" ADD CONSTRAINT "fk_VORSIGNAL_PERSONAL_TYP" FOREIGN KEY ("PERSONAL_TYP_ID") REFERENCES "StadtlaufBS"."PERSONAL_TYP" ("PERSONAL_TYP_ID");
ALTER TABLE "StadtlaufBS"."DISPOSITIV" ADD CONSTRAINT "fk_DISPOSITIV_POSITION" FOREIGN KEY ("POSITION_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."POSITION" ADD CONSTRAINT "fk_POSITION_POSITION_TYP" FOREIGN KEY ("POSITION_TYP_ID") REFERENCES "StadtlaufBS"."POSITION_TYP" ("POSITION_TYP_ID");
ALTER TABLE "StadtlaufBS"."POSITION" ADD CONSTRAINT "fk_POSITION_LIEFER_POS" FOREIGN KEY ("LIEFER_POS_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."MATERIAL" ADD CONSTRAINT "fk_MATERIAL_LIEFERART" FOREIGN KEY ("LIEFERART_ID") REFERENCES "StadtlaufBS"."LIEFERART" ("LIEFERART_ID");
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" ADD CONSTRAINT "fk_SEKTOR_AKTIV_POSITION_BS" FOREIGN KEY ("BESAMMLUNG_ORT_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."EINSATZ" ADD CONSTRAINT "fk_EINSATZ_HELFER" FOREIGN KEY ("HELFER_ID") REFERENCES "StadtlaufBS"."HELFER" ("HELFER_ID");
ALTER TABLE "StadtlaufBS"."SEKTOR_AKTIV" ADD CONSTRAINT "fk_SEKTOR_AKTIV_POSITION_LF" FOREIGN KEY ("POSITION_LIEFERUNG_ID") REFERENCES "StadtlaufBS"."POSITION" ("POSITION_ID");
ALTER TABLE "StadtlaufBS"."DOK_INHALT" ADD CONSTRAINT "fk_DOK_INHALT_SEKTOR_TYP" FOREIGN KEY ("SEKTOR_TYP_ID") REFERENCES "StadtlaufBS"."SEKTOR_TYP" ("SEKTOR_TYP_ID");
ALTER TABLE "StadtlaufBS"."SEKTOR" ADD CONSTRAINT "fk_SEKTOR_SEKTOR_TYP" FOREIGN KEY ("SEKTOR_TYP_ID") REFERENCES "StadtlaufBS"."SEKTOR_TYP" ("SEKTOR_TYP_ID");
ALTER TABLE "StadtlaufBS"."EINSATZ" ADD CONSTRAINT "fk_EINSATZ_BESATZUNG" FOREIGN KEY ("BESATZUNG_ID") REFERENCES "StadtlaufBS"."BESATZUNG" ("BESATZUNG_ID");
ALTER TABLE "StadtlaufBS"."BELIEFERUNG" ADD CONSTRAINT "fk_BELIEFERUNG_SEKTOR_DISPO" FOREIGN KEY ("SEKTOR_AKTIV_ID_DISPO") REFERENCES "StadtlaufBS"."SEKTOR_AKTIV" ("SEKTOR_AKTIV_ID");
ALTER TABLE "StadtlaufBS"."BELIEFERUNG" ADD CONSTRAINT "fk_BELIEFERUNG_SEKTOR_LFRG" FOREIGN KEY ("SEKTOR_AKTIV_ID_LFRG") REFERENCES "StadtlaufBS"."SEKTOR_AKTIV" ("SEKTOR_AKTIV_ID");
ALTER TABLE "StadtlaufBS"."DOK_INHALT" ADD CONSTRAINT "fk_DOK_INHALT_LIEFERART" FOREIGN KEY ("LIEFERART_ID") REFERENCES "StadtlaufBS"."LIEFERART" ("LIEFERART_ID");

GRANT USAGE ON SCHEMA "StadtlaufBS" TO pentahorep;
GRANT SELECT
  ON ALL TABLES IN SCHEMA "StadtlaufBS"
  TO pentahorep;
