-- Change Passwort
ALTER ROLE pentahorep PASSWORD 'evtDOK';

-- Passwort (encrypted)
SELECT rolpassword FROM pg_authid
WHERE rolname = 'pentahorep';


-- COPY Sektor-Aktiv auf neuen Anlass
INSERT INTO DISPO."SEKTOR_AKTIV"
            ("AUSTRAGUNG_ID", "SEKTOR_ID", "SEKTOR_CHEF", "BESAMMLUNG_ORT_ID", "BESAMMLUNG_ZEIT", "SEKTOR_SORT")
SELECT 6 AS "AUSTRAGUNG_ID", "SEKTOR_ID", "SEKTOR_CHEF", "BESAMMLUNG_ORT_ID", "BESAMMLUNG_ZEIT", "SEKTOR_SORT"
 FROM DISPO."SEKTOR_AKTIV"
  WHERE "AUSTRAGUNG_ID" = 5
    AND "SEKTOR_ID" IN(2,3,8,9,13,17,18,19,20,23,27);

-- COPY Dispositiv auf neuen Anlass
INSERT INTO DISPO."DISPOSITIV"
            ("SEKTOR_AKTIV_ID", "POSITION_ID", "POSITION_NR", "POSITION_ZUS",
             "RAYON_AKTIV_ID", "ABSCHNITT_AKTIV_ID",
             "POSITION_LIEFERUNG_ID")
SELECT "SEKTOR_NEU"."SEKTOR_AKTIV_ID", "POSITION_ID", "POSITION_NR", "POSITION_ZUS",
       "RAYON_NEU"."SEKTOR_AKTIV_ID" AS "RAYON_AKTIV_ID", "ABSCHNITT_NEU"."SEKTOR_AKTIV_ID" AS "ABSCHNITT_AKTIV_ID",
       "POSITION_LIEFERUNG_ID"
 FROM DISPO."DISPOSITIV"
 JOIN DISPO."SEKTOR_AKTIV" AS "SEKTOR_ALT" ON DISPO."DISPOSITIV"."SEKTOR_AKTIV_ID" = "SEKTOR_ALT"."SEKTOR_AKTIV_ID"
 JOIN DISPO."SEKTOR_AKTIV" AS "SEKTOR_NEU" ON "SEKTOR_ALT"."SEKTOR_ID" = "SEKTOR_NEU"."SEKTOR_ID" AND "SEKTOR_NEU"."AUSTRAGUNG_ID" = 6
 JOIN DISPO."SEKTOR_AKTIV" AS "RAYON_ALT" ON DISPO."DISPOSITIV"."RAYON_AKTIV_ID" = "RAYON_ALT"."SEKTOR_AKTIV_ID"
 JOIN DISPO."SEKTOR_AKTIV" AS "RAYON_NEU" ON "RAYON_ALT"."SEKTOR_ID" = "RAYON_NEU"."SEKTOR_ID" AND "RAYON_NEU"."AUSTRAGUNG_ID" = 6
 JOIN DISPO."SEKTOR_AKTIV" AS "ABSCHNITT_ALT" ON DISPO."DISPOSITIV"."ABSCHNITT_AKTIV_ID" = "ABSCHNITT_ALT"."SEKTOR_AKTIV_ID"
 JOIN DISPO."SEKTOR_AKTIV" AS "ABSCHNITT_NEU" ON "ABSCHNITT_ALT"."SEKTOR_ID" = "ABSCHNITT_NEU"."SEKTOR_ID" AND "ABSCHNITT_NEU"."AUSTRAGUNG_ID" = 6
  WHERE "SEKTOR_ALT"."AUSTRAGUNG_ID" = 5
    AND "RAYON_ALT"."AUSTRAGUNG_ID" = 5
    AND "ABSCHNITT_ALT"."AUSTRAGUNG_ID" = 5
    AND "SEKTOR_ALT"."SEKTOR_ID" IN(17,18,19,20,23,27);
